# Generated by Django 2.2.3 on 2019-12-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsellModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
