# Generated by Django 2.2.3 on 2019-12-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_productsellmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('bid_price', models.FloatField()),
                ('info', models.TextField()),
                ('p_image', models.ImageField(upload_to='products/')),
                ('status', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserregisterModel')),
            ],
        ),
    ]
