# Generated by Django 2.2.3 on 2019-12-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sellproductmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidtableModel',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('bid_ammount', models.FloatField()),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('time_of_join', models.TimeField(auto_now_add=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SellProductModel')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserregisterModel')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductsellModel',
        ),
    ]
